$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command  # This is correct for trial definitions
name: train_model
display_name: train_model
inputs: 
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  n_estimators:
    type: string
    default: "100"
  max_depth:
    type: string
    default: "5"
  criterion:
    type: string
    default: "squared_error"
outputs:
  model_output:
    type: mlflow_model
code: ../../../data-science/src
command: >
  python train.py
  --train_data \$\{{inputs.train_data}}
  --test_data \$\{{inputs.test_data}}
  --model_output \$\{{outputs.model_output}}
  --n_estimators \$\{{inputs.n_estimators}}
  --max_depth \$\{{inputs.max_depth}}
  --criterion \$\{{inputs.criterion}}


environment: azureml:used-crs-sales-train-env@latest
